### ISSUE TITLE
Dynamic class grid not paging properly

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-dotnet#61]
I have a dynamic grid using Roslyn for class generation, but the pagination doesn't work properly and seams to be Tubular back-end.

**Comment by mariodivece** [comment]
I concur. For example, I noticed I have to compute the response's total pages because it is wrong.
Check out:
https://github.com/unosquare/tubular-dotnet/blob/6923205764a78eafe627e0a7c4a392c4fbdebd15/src/Unosquare.Tubular/Extensions.cs#L106

it's supposed to be the following instead.
```csharp
var totalPages = (filteredCount / pageSize) + (filteredCount % pageSize > 0 ? 1 : 0);
```

with the current code, a filtered count of say, 180 and a pageSize of say 50, totalPages is set to 3 but there are 4 totalPages in reality.

**Comment by geoperez** [comment]
I applied your change, but an unit test is failing. I need to review it.
